### ISSUE TITLE
Given when craft fail with chance ratio, the object at target allows user to do again

### ISSUE THREAD

**Issue by yukihito23** [salutesh/Exile_Scavenge#2]
Description:
When craft fails with the chance ratio, the object at target allows user to do the same process again, which means user is told "couldn't find anything" but still allows user to keep on trying until they get something. To keep people on their feet, might as well allow block user from scavenging same object even if it fails initial check with chance.
Env:
Ver: 2017/10/16
Env: Exile 1.0.3 / Chernarus Redux v0.41

Steps to Repro:
1. Make given craft ratio to something very low (example: water)
2. start server
3. find water barrel or pump in server
4. start craft water
5. observe fail
6. try again

expected results:
the object at target shall not allow user to try to craft again, as they have already tried and are told they couldn't

actual results:
the object at question keeps allowing user to try to craft

**Comment by salutesh** [comment]
Confimed! 
Will be fixed with the next update.
