### ISSUE TITLE
Given the lapse time needed to craft or scavenge, the settings should be definable in config

### ISSUE THREAD

**Issue by yukihito23** [salutesh/Exile_Scavenge#4]
Given the time needed for crafting or scavenging to finish, it would be good if the amount of time needed can be defined within the config file.

GIVEN crafting / Scavenging
WHEN the amount of time needed is able to be set within configs
THEN server admins can change around the time depending on how complex the action is
AND makes it easier to customize this value

**Comment by salutesh** [comment]
Proposal accepted and it will be implemented with the next update.
