### ISSUE TITLE
ObfuSQF 

### ISSUE THREAD

**Issue by h0nkX** [salutesh/Exile_Scavenge#8]
Hey, 

know this might be more or less a thirdparty problem but i noticed. once you obfuscate the missionfile with ObfuSQF, some exile and third party script scrollwheel related actions (unlock, lock, claim vehicle and so on) 
are removed.

Cheers

**Comment by salutesh** [comment]
That is strange but maybe a kind of security thing of the module like Infistar is blocking not withelisted actions. Use the official BI Tools to pack your mission file and everything will be fine.

**Comment by h0nkX** [comment]
Regarding to obfusqf it's about _caller and _target beeing obfuscated too - welp, ppl have to wait for fix from obfusqf.
